# Generated by Django 2.1.2 on 2019-03-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='topic_public',
            field=models.ManyToManyField(blank=True, null=True, to='publications.Topic'),
        ),
    ]
