# Generated by Django 2.1.1 on 2018-09-27 14:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180921_1425'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('ctx', ckeditor_uploader.fields.RichTextUploadingField(db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Раздел')),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.AddField(
            model_name='publick',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Section'),
        ),
    ]
