# Generated by Django 2.1.1 on 2018-09-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180921_1425'),
        ('publications', '0002_auto_20180927_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publick',
            new_name='Public',
        ),
    ]
