# Generated by Django 2.1.2 on 2019-03-25 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_public_topic_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='publications.Section'),
        ),
        migrations.AlterField(
            model_name='public',
            name='topic_public',
            field=models.ManyToManyField(blank=True, to='publications.Topic'),
        ),
    ]
