# Generated by Django 2.1.1 on 2018-09-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20180927_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='publication',
            field=models.BooleanField(default=False),
        ),
    ]
