# Generated by Django 2.1.2 on 2019-03-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20190325_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='publications.Section'),
        ),
    ]
