# Generated by Django 2.1.1 on 2018-09-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_public_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default='2018-09-27 12:11'),
            preserve_default=False,
        ),
    ]
