# Generated by Django 2.1.2 on 2018-10-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, unique=True, verbose_name='Никнейм(логин)')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('code', models.CharField(max_length=200, null=True, verbose_name='Код активации')),
                ('activate', models.BooleanField(default=False, verbose_name='Активный')),
            ],
        ),
    ]
